imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*, build/coverage/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 7.4
    environment:
        variables:
            APP_ENV: 'testing'
            DB_DATABASE: 'database.sqlite'
    tests:
        before:
            - cp .env.scrutinizer .env
            - cp database.sqlite database.sqlite
        override:
            -
                command: "make phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
